# Generated by Django 3.0.5 on 2022-06-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=40)),
                ('total_copies', models.CharField(max_length=40)),
                ('available_copies', models.CharField(choices=[('1', '1000'), ('2', '2000'), ('3', '3000')], default='abc', max_length=6)),
            ],
        ),
    ]
